version: '3.4'

networks:
  dev:
    driver: bridge 

services:
  api:
    container_name: api-gateway
    image: api_gateway
    networks:
      - dev
    ports:
      - "8080:8080"

  tracks:
    container_name: tracks
    image: tracks_service
    networks:
      - dev
    ports:
      - "5000:5000"

  playlists:
    container_name: playlists
    image: playlists_service
    networks:
      - dev
    ports:
      - "5001:5001"

  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=music-browser
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/ 
    networks:
      - dev

volumes:
  db_data: